version: '3.9'
services: 
    main:
        build: .
        command: >
            sh -c "
                php /app/artisan key:generate &&
                php /app/artisan migrate:fresh --seed &&
                php /app/artisan serve --host=0.0.0.0:8000
            "
        ports:
            - 8000:8000
        depends_on: 
            - db
        networks:
            app_net:
                ipv4_address: 172.16.123.10
        restart: on-failure

    db:
        platform: linux/x86_64
        image: mariadb:latest
        environment: 
            MARIADB_DATABASE: laravel
            MARIADB_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        networks:
            app_net:
                ipv4_address: 172.16.123.20
        restart: on-failure


networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: 172.16.123.0/24
                  gateway: 172.16.123.1
